name: robust
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - pandas
  - networkx
  - pip
  - jupyter
  - pip:
    - ipycytoscape==1.0.4
    - ipywidgets==7.5.1
    - pcst-fast==1.0.7
    - ndex2
